<a href="https://colab.research.google.com/github/youssefsalah224/AI-Engineer-KidSafe-Alphabet-Tutor/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
mat=np.arange(1,31).reshape(6,5)

In [ ]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
mat[2:4,0:2]

array([[11, 12],
       [16, 17]])

In [ ]:
new_mat = np.eye(6, 5, k=1, dtype=int)

In [ ]:
matt=new_mat*mat
matt

array([[ 0,  2,  0,  0,  0],
       [ 0,  0,  8,  0,  0],
       [ 0,  0,  0, 14,  0],
       [ 0,  0,  0,  0, 20],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0]])

In [ ]:
matrix = np.zeros((6, 5), dtype=int)
pos=[(0,3),(0,4),(4,3),(4,4),(5,3),(5,4)]
for r,c in pos:
 matrix[r,c]=1

new_mattt=matrix*mat
new_mattt

array([[ 0,  0,  0,  4,  5],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0, 24, 25],
       [ 0,  0,  0, 29, 30]])

In [ ]:
new=np.arange(10)
new

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
idn=np.eye(3,3)
idn

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
odd= new[new%2==1]
odd

array([1, 3, 5, 7, 9])

In [ ]:
arr2 = np.arange(1, 13).reshape(3, 4)
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
np.random.rand(5, 5)

array([[0.8083673 , 0.61280358, 0.38952187, 0.61619605, 0.27176004],
       [0.52860372, 0.53705692, 0.53722465, 0.39277218, 0.26089984],
       [0.43354413, 0.46266356, 0.28580673, 0.87392761, 0.20876544],
       [0.09897712, 0.13645294, 0.54547536, 0.47619421, 0.60516952],
       [0.8263878 , 0.17135296, 0.9238149 , 0.1218594 , 0.9972366 ]])

In [ ]:
matrix1 = np.random.randint(1, 10, (5, 3))
matrix2 = np.random.randint(1, 10, (3, 2))
product = np.dot(matrix1, matrix2)
product

array([[44, 64],
       [66, 56],
       [69, 72],
       [46, 36],
       [18, 24]])

In [ ]:
arr = np.arange(11)
arr[(arr >= 3) & (arr <= 8)] *= -1
arr

numm=np.arange(0,10)
newnum=np.array([1,1,1,-1,-1,-1,-1,-1,1,1])
arr=numm*newnum
arr

array([ 0,  1,  2, -3, -4, -5, -6, -7,  8,  9])